//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace registration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reg
    {
        public int regsid { get; set; }
        public string regsname { get; set; }
        public Nullable<decimal> regsrollno { get; set; }
        public Nullable<decimal> regsage { get; set; }
        public string regsemailid { get; set; }
        public Nullable<decimal> regscontactno { get; set; }
    }
}
